---
title: "DTU_quantification_CRM"
date: "5/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

data_folder <- "~/sp-data/paper0_au_validering/D1.b/"
source("r/sp_funs.R")
```

##


```{r classification}
tic("classifier")
classified <- data_folder %>% sp_classifier(RM_string = "60 nm Au 100 ng/l RM")
toc("classifier")
```


```{r particles}

{tic("particles")
peaked <- sp_peaker(classified)
toc("particles")}
```


```{r, warning=FALSE}
{tic("cal")
calibration_data <- sp_calibrator(classified, RM_dia = 60, RM_density =  19.32, element_fraction = 1, RM_isotope = "Au")
toc("cal")}
```


```{r}
tic("pout")
particles_out <- sp_outputer(peaked, calibration_data, dens_comps, RM_isotope = "60 nm Au 100 ng/l RM", sample_intake_rate = 0.346, acq_time = 120)
toc("pout")
```


```{r, warning=FALSE, message=FALSE}
tic("wraptesting")
wraptest2 <- sp_wrapper(data_folder,
                        acq_time = 120,
                        sample_intake_rate = 0.346,
                        RM_string = "60 nm Au 100 ng/l RM",
                        dens_comps = dens_comps,
                        RM_isotope = "Au",
                        RM_dia = 60)
toc("wraptesting")


```

```{r validation}
sp_spectrum_validation(s_name = "60 nm Au 100 ng/l RM", dfile = "024SMPL_D1", sp_output = wraptest2) %>% mutate(time = row_number()) %>% 
  ggplot(aes(time, counts))+geom_line()
```

